language: php

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

php:
- 5.6
- 7
- 7.1

before_install:
  - echo '{"http-basic": {"repo.magento.com": {"username": $MAGENTO_PUBLIC_KEY,"password": $MAGENTO_PRIVATE_KEY}}}' >> auth.json

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test