dist: trusty
sudo: false
language: php

addons:
  sonarqube:
    organization: "wirecard"
    token:
      secure: "BlSEqQSC0DrjJsarQU2obCgOAcFLFTT9mNr/m3X/3+nkC9woXrZIQch9SzSX5RM8r21CNuweieI4I/D4s4wvGIvmTZ1rSoUrfp5U5JtYDnQPUP5jWR+31looGmiiAA8vGaTZZv/f4u7k/jedglDNrA8/Mm7IU8M9KCBO4HQJqZYGc72VhXHl8ynGyfwndngLSnBj2fjbECjFrPVwoayAgjMsyXnvXZUam7zTUp6KOX1U7FdY4mDAHmypF0dPGAMM1UCNh0Tvc9wjpkzlBlY6CkYvLYAzjLeRPaeukCnLLHpvPmoS1C6KGhx+bfuAZQ1ygk5FDsyA10LAVTtPnOAjQo4IF7U9oLNvZzOSeR7X57WWkA9PJuAHL3+RSH3ceCUktsAVX1pyb9VlIjEXcQSF45Mmb4Eg0bw26BAClJaZbSjHt3VYTpHpnZiNh1ae104wAg3et9KyzfNOl0J4KqXftt7RmRgNTHEOxLBbJNzEKddwcrRhJLvW1yfoEIAel336pHuEbXRXqI+WNgVW7iqppKIoCpy0R6SgGfjZ6R9UXagtjIO3X6pnW5Jn/4ajAdOHzhJtGDnjksDXMjp7wGxuGUqA6vLfxFPt90F+HDHUsceVXriUJ30vrH3lDuKVPT/QI4EC2nY9vjfSzbSJIJYROy0CNG7TJwpVG7RPtS+ZaQY="
    github_token:
      secure: "hGovnzy2vP+v2eknvhQJv6l9XmYTUJU0dkkz0wu2V76mtPs+OS51GoigBs3MPDbC7aY9xm5x1nAr/1rOtmluJAIcUhl2FHkUQ767R6rQLBUjt7y+qMZrgtqDgS5X5MQAu1g86mxK1LWr97JO59CW047gNA7tDfmt+hafH6D69yroU/Go8Xn2wT0g2D+6a++zEqxeKklve98uj5gxeX7IF7E/Gh4CTsZ//NJItQFnx5NeDHFlEH6HEKq4lNO3eRmukUjzQaw/COvTLuOnLBRy9WSFuSbODpxl9McaRyv5Qy84wihKkwvOLxjIKGPXwD4l4M8r0uzn8zoX5yDShFNyEpJllS+S2UzLlvvhQ9KEzEpbBH8El5ZhdqK53Yrp6Cw5ax2jXI+I8GHnRds8ybWw+mpmPsbhCB53MpRYNe5SnT3t8yES63PtE8r7QOKolH260zUYMQsy/9fiQb7g0WQySrMAxG9wCfSfL2PnJgImgoupUXNtWwdX3s+VLBKfBXcE1L1bu5uc6Hgp6XmE5R41nXyTRvBgBnG4QnOhUKklJ0/H4W+fJ2FilVsF6RGW6Vk7aiJ102KI8QWGgrP+WrSmV5CQIgOTdLmZ49zE99/JnrvTxrrZXsoAU8js9zqNOPS6KAKrbQ8tUYXee52I87E9BOWEpN/G0F4zF4BT6+ucXME="

env:
  global:
  - COMPOSER_ARGS="--no-interaction"

php:
- 5.6
- 7
- 7.1

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show

script:
  - composer test
  - sonar-scanner
