version: '3.0'
services:
  web:
    container_name: "${MAGENTO_CONTAINER_NAME}"
    image: alexcheng/magento2
    ports:
      - "9090:80"
    links:
      - db
    env_file:
      - env
    environment:
      MAGENTO_URL: "${NGROK_URL}"
  db:
    image: mysql:5.6.23
    env_file:
      - env
    command:
      - --wait_timeout=1000
